/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author XT
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        pswFContraseña = new javax.swing.JPasswordField();
        lblCreadores1 = new javax.swing.JLabel();
        lblCreadores = new javax.swing.JLabel();
        txtfUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(490, 220));
        setMinimumSize(new java.awt.Dimension(490, 220));
        setPreferredSize(new java.awt.Dimension(490, 220));
        getContentPane().setLayout(null);

        btnIngresar.setBackground(new java.awt.Color(15, 17, 26));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(186, 221, 134));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 221, 134), 3));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(212, 139, 127, 35);

        btnAtras.setBackground(new java.awt.Color(15, 17, 26));
        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(186, 221, 134));
        btnAtras.setText("ATRAS");
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 221, 134), 3));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(78, 139, 100, 35);

        pswFContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswFContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(pswFContraseña);
        pswFContraseña.setBounds(180, 70, 166, 30);

        lblCreadores1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCreadores1.setForeground(new java.awt.Color(186, 221, 134));
        lblCreadores1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreadores1.setText("Contraseña: ");
        getContentPane().add(lblCreadores1);
        lblCreadores1.setBounds(80, 70, 100, 22);

        lblCreadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCreadores.setForeground(new java.awt.Color(186, 221, 134));
        lblCreadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreadores.setText("Usuario: ");
        getContentPane().add(lblCreadores);
        lblCreadores.setBounds(90, 30, 71, 22);
        getContentPane().add(txtfUsuario);
        txtfUsuario.setBounds(180, 30, 166, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Administrador.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        JFrame menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String usuario = txtfUsuario.getText();
        String password = pswFContraseña.getText();
        if(usuario.equals("admin") && password.equals("123456")){
            JFrame crear = new Creador();
            crear.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void pswFContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswFContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswFContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCreadores;
    private javax.swing.JLabel lblCreadores1;
    private javax.swing.JPasswordField pswFContraseña;
    private javax.swing.JTextField txtfUsuario;
    // End of variables declaration//GEN-END:variables
}
