/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JPanel;






/**
 *
 * @author XT
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCreadores = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnNueva = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(670, 510));
        setMinimumSize(new java.awt.Dimension(670, 510));
        setSize(new java.awt.Dimension(670, 510));
        getContentPane().setLayout(null);

        lblCreadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCreadores.setForeground(new java.awt.Color(255, 0, 0));
        lblCreadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreadores.setText("Daniel B. & Josué G.");
        getContentPane().add(lblCreadores);
        lblCreadores.setBounds(370, 430, 177, 72);

        btnCrear.setBackground(new java.awt.Color(0, 0, 0));
        btnCrear.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 0, 0));
        btnCrear.setText("Crear guerreros");
        btnCrear.setBorder(null);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(330, 250, 200, 52);

        btnNueva.setBackground(new java.awt.Color(0, 0, 0));
        btnNueva.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        btnNueva.setForeground(new java.awt.Color(255, 0, 0));
        btnNueva.setText("Nueva partida");
        btnNueva.setBorder(null);
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNueva);
        btnNueva.setBounds(330, 180, 200, 52);

        btnCargar.setBackground(new java.awt.Color(0, 0, 0));
        btnCargar.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 0, 0));
        btnCargar.setText("Cargar partida");
        btnCargar.setBorder(null);
        btnCargar.setPreferredSize(new java.awt.Dimension(132, 30));
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar);
        btnCargar.setBounds(330, 120, 200, 52);

        lblTitulo.setFont(new java.awt.Font("Bernard MT Condensed", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Clash of Empires");
        lblTitulo.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(290, 30, 288, 72);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoMenu.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
        JFrame tableroPrincipal = new tableroPrincipal();
        tableroPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        JFrame administrador = new Administrador();
        administrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ImagePanel panel = new ImagePanel(new ImageIcon("C:\\Users\\XT\\Documents\\POO\\ClashOfClans-main\\src\\Imagenes\\fondoMenu").getImage());
               
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCreadores;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
