/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fichas.GUITools.Juego;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author PERSONAL
 */
public class tableroPrincipal extends javax.swing.JFrame {
     Juego juego;
     ArrayList<JLabel> arregloGuerreros;
     ArrayList<JLabel> arregloEnemigos;
     ArrayList<JLabel> arregloEstructuras;

    /**
     * Creates new form tableroPrincipal
     */
    public tableroPrincipal() {
        juego = new Juego(this);
        arregloGuerreros = new ArrayList<JLabel>();
        arregloEnemigos = new ArrayList<JLabel>();
        arregloEstructuras = new ArrayList<JLabel>();
        initComponents();
    }
    

    /**
     * Creates new form FramePrincipal
     
     * @return 
     */
   

    public JLabel generateLabel(){
        JLabel newLabel = new JLabel("#");
        newLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newLabel.setForeground(new java.awt.Color(255, 255, 255));
        newLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newLabel.setSize(140, 40);
        campoGuerra.add(newLabel);
        newLabel.setBackground(Color.red);
        newLabel.setOpaque(true);
        
        int x = ((new Random()).nextInt(1000)/40) * 40;
        int y = ((new Random()).nextInt(600) / 40)* 40;
        newLabel.setLocation(x , y);
        arregloEstructuras.add(newLabel);
        
        return newLabel;
    }
    
    public void moveLabel (int listIndex){
            
        JLabel refLabel = arregloGuerreros.get(listIndex);
        
        int direccion = (new Random()).nextInt(4);
        int x = refLabel.getLocation().x;
        int y = refLabel.getLocation().y;
        
        //sumo A x O y
            if (direccion == 0 && y-40 >= 0) //arriba
                y = y-40;
            else if (direccion == 1 && y+40 <= 560)
                y = y+40;
            else if (direccion == 2 && x+40 <= 800)
                x = x+40;
            else if (direccion == 3 && x-40 >= 0)
                x = x-40;
            
        
        int ocupadoPor = isAvailablePostion(x, y, refLabel);
        if (ocupadoPor == -1)
            refLabel.setLocation(x, y);
        else
            System.out.println("Esta ocupada " + x + "," + y + " por " + arregloGuerreros.get(ocupadoPor).getText());
    }
    
    public int isAvailablePostion(int x, int y, JLabel refLabel){      
        
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoGuerra = new javax.swing.JPanel();
        lblNivel = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btbReStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaOpciones = new javax.swing.JTextArea();
        txtaNombreGuerrero = new javax.swing.JTextField();
        btbSkip = new javax.swing.JButton();
        lblEspacios = new javax.swing.JLabel();
        lblInstruccion = new javax.swing.JLabel();
        lblCantAliados = new javax.swing.JLabel();
        lblCantAliados1 = new javax.swing.JLabel();
        lblCantAliados2 = new javax.swing.JLabel();
        lblCantAliados3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));

        campoGuerra.setBackground(new java.awt.Color(102, 255, 51));
        campoGuerra.setForeground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout campoGuerraLayout = new javax.swing.GroupLayout(campoGuerra);
        campoGuerra.setLayout(campoGuerraLayout);
        campoGuerraLayout.setHorizontalGroup(
            campoGuerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        campoGuerraLayout.setVerticalGroup(
            campoGuerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblNivel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNivel.setText("1");

        btnStart.setText("START");

        btnGenerate.setText("GENERATE");

        btbReStart.setText("RE-START");

        txtaOpciones.setColumns(20);
        txtaOpciones.setRows(5);
        jScrollPane1.setViewportView(txtaOpciones);

        txtaNombreGuerrero.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtaNombreGuerrero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaNombreGuerrero.setText("Personaje");

        btbSkip.setText("SKIP LVL");

        lblEspacios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEspacios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspacios.setText("1");

        lblInstruccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInstruccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccion.setText("Ingrese el nombre del Guerrero");

        lblCantAliados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantAliados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantAliados.setText("0");

        lblCantAliados1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantAliados1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantAliados1.setText("Cantidad de Aliados");

        lblCantAliados2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantAliados2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantAliados2.setText("0");

        lblCantAliados3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantAliados3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantAliados3.setText("Cantidad de Enemigos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btbReStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(lblEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtaNombreGuerrero, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(campoGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btbSkip)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantAliados2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantAliados, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantAliados3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantAliados1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campoGuerra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEspacios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtaNombreGuerrero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCantAliados1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantAliados2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantAliados3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantAliados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbReStart, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btbSkip)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableroPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbReStart;
    private javax.swing.JButton btbSkip;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel campoGuerra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantAliados;
    private javax.swing.JLabel lblCantAliados1;
    private javax.swing.JLabel lblCantAliados2;
    private javax.swing.JLabel lblCantAliados3;
    private javax.swing.JLabel lblEspacios;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JTextField txtaNombreGuerrero;
    private javax.swing.JTextArea txtaOpciones;
    // End of variables declaration//GEN-END:variables
}
